---
- hosts: all
  gather_facts: true
  become: true
  roles:
    - role: zsh
      tags: zsh
    - role: multipass
      tags: multipass
    - role: libvirt
      tags: libvirt
    - role: geerlingguy.docker
      tags: docker
