#cloud-config

package_update: true
package_upgrade: true
password: Passw0rd
ssh_pwauth: true
chpasswd:
  expire: false
users:
  # - name: root
  #   lock_passwd: false
  #   # shell: /bin/bash
  #   chpasswd: { expire: False }
  #   plain_text_passwd: Passw0rd
  - name: mandy
    sudo: ALL=(ALL) NOPASSWD:ALL
    lock_passwd: false
    shell: /bin/bash
    chpasswd: { expire: False }
    plain_text_passwd: Passw0rd

packages:
  - sudo
  - fuse-overlayfs

runcmd:
  # https://rootlesscontaine.rs/
  - curl -sfL https://get.k3s.io | sh - --rootless
