#cloud-config

# package_update: true
# package_upgrade: true
ssh_pwauth: true
debug: true
users:
  # - name: root
  #   lock_passwd: false
  #   # shell: /bin/bash
  #   chpasswd: { expire: False }
  #   plain_text_passwd: Passw0rd
  - name: mandy
    sudo: ALL=(ALL) NOPASSWD:ALL
    lock_passwd: false
    shell: /bin/bash
    chpasswd: { expire: False }
    plain_text_passwd: Passw0rd
packages:
  - sudo
