#cloud-config

package_update: true
package_upgrade: true

runcmd:
  - curl -sL https://github.com/ohmymndy.keys | tee -a /home/ubuntu/.ssh/authorized_keys
  - chown ubuntu:ubuntu -R /home/ubuntu/.ssh
